app/models/__init__.py
from .greenhouse import Greenhouse
from .sample import Sample

__all__ = (
    "Greenhouse",
    "Sample"
)

app/models/greenhouse.py
from dataclasses import dataclass


@dataclass
class Greenhouse:
    id: int
    serial: str

app/models/sample.py
from datetime import datetime
from dataclasses import dataclass


@dataclass
class Sample:
    id: int
    created: datetime
    humidity: float
    temperature: float
    humidifier_state: int
    fan_state: int
    lights_state: int
    greenhouse_id: int

app/__init__.py
import contextlib
from flask import Flask

from app.controllers import dashboard_ns, sample_ns
from app.db.connection import current_local, initialize_tables


def create_app(config_file):
    app = Flask(__name__)
    app.config.from_pyfile(config_file)
    app.register_blueprint(dashboard_ns)
    app.register_blueprint(sample_ns)
    with app.app_context():
        with contextlib.closing(current_local.connection) as connection:
            initialize_tables(connection)
    return app

app/controllers/__init__.py
from .dashboard_controller import dashboard_ns
from .sample_controller import sample_ns

app/controllers/dashboard_controller.py
import contextlib
import logging

from flask import Blueprint, render_template

from app.db.connection import current_local
from app.services.sample_service import select_latest_sample_for_all


logger = logging.getLogger(__name__)
dashboard_ns = Blueprint("dashboard", __name__, url_prefix="/dashboard")


@dashboard_ns.route("/")
def index():
    with contextlib.closing(current_local.connection.cursor()) as cursor:
        greenhouses = select_latest_sample_for_all(cursor)
    return render_template(
        "index.html",
        greenhouses=greenhouses
    )

app/controllers/sample_controller.py
import contextlib
import logging
from dataclasses import asdict

from flask import Blueprint, request, abort

from app.db.connection import current_local
from app.services.sample_service import insert_sample, select_latest_sample_for_serial

logger = logging.getLogger(__name__)
sample_ns = Blueprint("greenhouse", __name__, url_prefix="/greenhouse")


SUCCESS_MESSAGE = "OK"


def prepare_message_response(message=SUCCESS_MESSAGE):
    return {
        "message": message
    }


@sample_ns.route("/<serial>/sample", methods=["POST"])
def create_sample(serial):
    with contextlib.closing(current_local.connection.cursor()) as cursor:
        try:
            insert_sample(cursor, serial=serial, **request.json)
        except TypeError:
            logger.exception("Invalid request.")
            return abort(400)
    return prepare_message_response()


@sample_ns.route("/<serial>/sample/latest", methods=["GET"])
def get_latest_sample(serial):
    with contextlib.closing(current_local.connection.cursor()) as cursor:
        sample = select_latest_sample_for_serial(cursor, serial)
    if not sample:
        return abort(404)
    return asdict(sample)

app/templates/index.html
{% block css %}
    <link href="{{ url_for('static', filename='css/home.css') }}" rel="stylesheet">
{% endblock %}
{% block content %}
    <div class="refresh-container">
        <a href="{{ url_for('dashboard.index') }}"><button>REFRESH</button></a>
    </div>
    {% for greenhouse in greenhouses %}
        <div class="greenhouse-container">
            <h1>{{ greenhouse["serial"] }}</h1>
            <ul>
                <li><b>Last Reading:</b> {{ greenhouse["created"] }}</li>
                <li><b>Humidity:</b> {{ "{:.2f}%".format(greenhouse["humidity"]) }}</li>
                <li><b>Temperature:</b> {{ "{:.2f} F".format(greenhouse["temperature"]) }}</li>
                <li><b>Fan:</b> {{ "on" if not greenhouse["fan_state"] else "off"}}</li>
                <li><b>Humidifier:</b> {{ "on" if not greenhouse["humidifier_state"] else "off"}}</li>
                <li><b>Lights:</b> {{ "on" if not greenhouse["lights_state"] else "off"}}</li>
            </ul>
        </div>
    {% endfor %}
{% endblock %}